NDLから書影を受け取るように修正
traPtitech/booQ-UI pull request #1101
Opened 2023-09-18 12:49 UTC by s9-sukyu

API: https://github.com/traPtitech/booQ/pull/542

2023-09-18 12:50 UTC, s9-sukyu commented on src/components/RegisterForm/composables/useCompleteFromCode.ts
> +    const res = await apis.itemsCheckNdlImageIsbnCodeGet(Number(formState.code))
openAPIで自動生成されたapiの名前がよくなさそうだけど改善方法がわかりません

2023-09-18 14:09 UTC, cp-20 commented on src/components/RegisterForm/composables/useCompleteFromCode.ts
> +    const res = await apis.itemsCheckNdlImageIsbnCodeGet(Number(formState.code))
この処理は必要なんでしょうか？
この結果によって分岐がありますが、ただURLを空にしているだけなので、別に404でもそのままimgUrlに突っ込んでしまってもいいのでは？と思いました。

2023-09-18 14:09 UTC, cp-20 commented on src/components/RegisterForm/composables/useCompleteFromCode.ts
> +    const res = await apis.itemsCheckNdlImageIsbnCodeGet(Number(formState.code))
仮にこの処理が必要ないとすると、バックエンドのPRそのものがいらなくなりそうですが

2023-09-20 00:31 UTC, cp-20 requested changes

2023-09-20 00:31 UTC, cp-20 commented on src/components/RegisterForm/composables/useCompleteFromCode.ts
> +import apis from '/@/lib/apis'
使われてないので消した方が良さそうです (Lintエラーが出てる)

2023-09-20 10:01 UTC, merged