ユーザー画面
traPtitech/booQ-UI pull request #289
Opened 2021-01-07 04:32 UTC by reyu0722

2021-01-08 10:59 UTC, ryoha000 reviewed
こんな感じの方向性でいいと思う
css書くのもここでやっちゃいましょう

2021-01-08 10:59 UTC, ryoha000 commented on src/pages/User.vue
> +      comments: [] as Comment[],
ここの`comments`は消して一時的な変数として持つようにするのでいいと思う
Mapでも`v-for`はできるけど読みやすさとかから`commentedItems`はarrayに

2021-04-05 05:42 UTC, ryoha000 requested changes
あとまわしにしてたらすっかり忘れてたごめんなさい
コメント表示部分のUIちょっと変えたいなってなったから変えてください(ごめん:pray:)
Figmaみたらわかると思います

2021-04-05 05:42 UTC, ryoha000 commented on src/pages/User.vue
> +      apis.getItems(state.username).then(({ data }) => {
`await` の方が読みやすいのでそうしてください:pray:

2021-04-05 05:42 UTC, ryoha000 commented on src/pages/User.vue
> +            .catch(() => null)
consoleにerror出すくらいはしてもよさそう

2021-04-05 05:42 UTC, ryoha000 commented on src/components/ItemWide/ItemWideGrid.vue
> +    slots: {
Vue使ってて`slot`っていうとDOM入れれるみたいだから`texts`みたいな感じの方がよさそう

2021-04-05 05:42 UTC, ryoha000 commented on src/pages/User.vue
> +      apis.getItems(state.username).then(({ data }) => {
あとPromise.allを使うのやめてますがどういう意図でしましたか？

2021-04-05 05:43 UTC, ryoha000 commented
@sapphi-red 
今書いてるところはこんな感じかなと思ったけどなんかあったら言ってくれたらうれしい

2021-04-30 10:38 UTC, reyu0722 commented on src/pages/User.vue
> +      apis.getItems(state.username).then(({ data }) => {
あれこれしてるときに変えて戻し忘れてるだけなので使います:pray:

2021-04-30 21:09 UTC, ryoha000 commented
@reyu0722 
masterのバージョンと合わせたいので
```
git fetch origin master
git rebase origin/master
```
でrebaseしてください:pray:

あと解決したと自分が思ったレビューは`resolve conversation`でとじてほしいです

2021-05-01 12:16 UTC, ryoha000 requested changes

2021-05-01 12:16 UTC, ryoha000 commented
@sapphi-red 
git 爆発しちゃった＞＜
ﾀｽｹﾃ...ﾀｽｹﾃ...

2021-05-01 14:00 UTC, ryoha000 commented
いけてそう:+1:

2021-05-01 19:38 UTC, reyu0722 commented on src/pages/User.vue
> +        )
`Promise.all` が拒否されないようにここでcatchしてたんですが、`Promise.allSettled` を使うならここじゃない方がよかったりしますか？

2021-05-01 19:59 UTC, ryoha000 commented on src/pages/User.vue
> +        )
あ～そうですね
ちょっと紛らわしかったですね

2021-05-02 06:18 UTC, reyu0722 commented on src/pages/User.vue
> +      state.comments = comments
今filter+map (+型のあれこれ) してるのがflatMap使うと楽にできそうなんですが、他に似たようなことしてるサイトとかがあんまり見つからなかったんですが使って大丈夫ですか？

https://zenn.dev/yarnaimo/articles/66e9102a79c0896b4204

2021-05-02 08:00 UTC, sapphi-red commented on src/pages/User.vue
> +      state.comments = comments
[`.flatMap`の対応状況](https://caniuse.com/array-flat)的には使っても問題ないです
(使ったほうがよいかは場合によりけりですが)

今回は、@ryoha000 くんがユーザーごとのコメント一覧取得API生やしてなくて、仮で書いてあるだけなのでどっちでもよいと思います

@ryoha000 これ実は生えてたりしない？未実装でswaggerだけある状態？ https://apis.trap.jp/?urls.primaryName=booQ#/comments/getComments

2021-05-02 11:42 UTC, ryoha000 commented on src/pages/User.vue
> +      state.comments = comments
生えてたわ:gahaha:

2021-05-02 11:43 UTC, ryoha000 commented on src/pages/User.vue
> +      state.comments = comments
いや、嘘
コメント一覧はあるんだけど返り値の中身にitemが生えてないんだったわ
今生やす

2021-05-03 11:12 UTC, ryoha000 commented on src/pages/User.vue
> +      state.comments = comments
@reyu0722 
やったんで
`npm run gen-api`したらitemも入ってると思います

2021-05-04 13:32 UTC, ryoha000 requested changes

2021-05-04 13:32 UTC, ryoha000 commented on src/components/UserPage/Comment.vue
> +  <div :class="$style.container" @click="onClick">
この@clickは一つ下のdivにあってほしい
コメントクリックしてアイテムに飛ぶのはびみょい気がする

2021-05-04 13:32 UTC, ryoha000 commented on src/components/UserPage/Comment.vue
> +      <slot />
ここはslotじゃなくてpropsでtextを受け取って表示するようにした方がよさそう
slotは中にコンポーネントを自由に置きたいときに使うイメージ

2021-05-04 13:32 UTC, ryoha000 commented on src/components/UserPage/CommentGrid.vue
> +  grid-template-columns: repeat(auto-fill, minmax(24rem, 1fr));
Itemsでは`minmax(12rem, 1fr)`だし合わせちゃって良さそう

2021-05-04 13:32 UTC, ryoha000 commented on src/components/ItemWide/ItemWideGrid.vue
> +<template>
使ってなさそう

2021-05-07 07:15 UTC, sapphi-red reviewed
良さそうです :pro:
あと細かいとことコンフリクトの解消をしてほしいです :pray:

2021-05-07 07:15 UTC, sapphi-red commented on src/components/UserPage/CommentGrid.vue
> +      type: Array as PropType<{ text: string; item: ItemSummary }[]>,
```suggestion
import { Comment as CommentType } from '/@/lib/apis'
import Comment from './Comment.vue'

export default defineComponent({
  name: 'CommentGrid',
  components: {
    Comment
  },
  props: {
    comments: {
      type: Array as PropType<CommentType[]>,
```
型が存在してるのでこれを使ったほうがいいです 🖖

2021-05-07 07:15 UTC, sapphi-red commented on src/pages/User.vue
> +      }))
```suggestion
      state.comments = comments
```
ここ(ほぼ)何もしてないのでそのまま代入してよいですね 🤘

2021-05-07 07:15 UTC, sapphi-red commented on src/pages/User.vue
> +      const [{ data: items }, { data: comments }] = await Promise.all([
両方ともに依存しているような処理はないのでそれぞれ別に書いたほうがよさそうです 😉 
別で書けば片方が終わった地点でそっちのほうの処理は行えるようになるので

```ts
watchEffect(async () => {
  const { data } = await apis.getItems(state.username)
  state.item = data
})
watchEffect(async () => {
  const { data } = await apis.getComments(state.username)
  state.comments = data
})
```

2021-05-07 07:15 UTC, sapphi-red commented on src/pages/User.vue
> +  display: flex;
```suggestion
  display: flex;
  align-items: center;
```
中央揃えにしたほうがよさそうです

2021-05-07 07:15 UTC, sapphi-red commented on src/pages/User.vue
> +      comments: [] as { text: string; item: ItemSummary }[]
ここも上で言った`Comment`型使ったほうが良いですね

2021-05-10 12:20 UTC, sapphi-red approved these changes
:yosa: :desu: :tada:

2021-05-10 12:20 UTC, merged