fix eslint prettier config
traPtitech/booQ-UI pull request #996
Opened 2022-05-14 11:39 UTC by ryoha000

2022-05-14 11:40 UTC, ryoha000 commented
ソースはqiita

2022-05-15 05:02 UTC, sapphi-red commented
eslintとprettierの設定方法じゃなくて、vscodeでprettierとeslintを衝突しないように初心者が設定できるソースを探してほしい :pray:

2022-05-15 06:09 UTC, ryoha000 commented
これでいいかな？
https://zenn.dev/ryusou/articles/nodejs-prettier-eslint2021#vscode%E3%81%AE%E8%A8%AD%E5%AE%9A%E3%81%AFeditor.codeactionsonsave%E3%81%A8editor.defaultformatter%E3%82%92%E8%A8%AD%E5%AE%9A%E3%81%97%E3%82%88%E3%81%86

2022-05-15 06:21 UTC, sapphi-red commented
それで意図通り動いたならよさそう

2022-05-15 06:23 UTC, sapphi-red requested changes

2022-05-15 06:23 UTC, sapphi-red commented on .vscode/settings.json
> +{
このファイルは含めないでほしい :pray:
SysAd/randomに投げたほうがいいとは思う

2022-05-15 06:23 UTC, sapphi-red commented on package.json
>      "eslint": "^8.15.0",
上のlintに`prettier --check`(みたいなの)追加してほしい :pray:

2022-10-05 12:30 UTC, closed without merging